spring.application.name=jobtracker

# Database Configuration
# Updated to match your Render Environment Keys
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Keep these for JPA management
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
jwt.secret=${JWT_SECRET}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG